language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: 
        - PIP=pip
        - CIBW_BUILD=cp27
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp27

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
